# Generated by Django 3.2.12 on 2022-08-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('width_height_units', models.CharField(choices=[('0', 'PIXELS'), ('1', 'PERCENT'), ('2', 'MILLIMETERS'), ('3', 'IMCHES')], default='1', max_length=20)),
                ('scale', models.FloatField(default=0)),
                ('name', models.TextField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='#FFFFFF', max_length=20, null=True)),
                ('dpi', models.FloatField(default=72.0)),
            ],
        ),
    ]
