# Generated by Django 3.2.12 on 2022-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='style',
            name='width_height_units',
            field=models.CharField(choices=[('0', 'PIXELS'), ('1', 'PERCENT'), ('2', 'MILLIMETERS'), ('3', 'IMCHES')], default='1', max_length=255),
        ),
    ]
