# Generated by Django 3.2.12 on 2022-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_auto_20220811_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='style',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='width_height_units',
            field=models.CharField(choices=[('0', 'PIXELS'), ('1', 'PERCENT'), ('2', 'MILLIMETERS'), ('3', 'IMCHES')], default='0', max_length=255),
        ),
    ]
