# Generated by Django 3.2.12 on 2022-08-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name_template', models.TextField(blank=True, max_length=255)),
                ('updated', models.DateTimeField()),
                ('type_template', models.CharField(choices=[('0', 'HOLIZONTAL'), ('1', 'VERTICAL'), ('2', 'SQUARE')], default='0', max_length=255)),
            ],
        ),
    ]
