# Generated by Django 3.2.12 on 2022-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_templates_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='name_template',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
