# Generated by Django 3.2.12 on 2022-08-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_auto_20220812_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templates',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Templates Boards'},
        ),
    ]
