# Generated by Django 3.2.12 on 2022-08-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_alter_templates_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
